random_seed: 42

model:
  name: "Qwen/Qwen2.5-0.5B-Instruct"
  # name: "Qwen/Qwen2.5-7B-Instruct"
  torch_dtype: "bfloat16"
  device_map: null

lora_config:
  r: 8
  lora_alpha: 32
  target_modules:
    - "q_proj"
    - "v_proj"
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

dataset:
  name: "medmcqa"
  num_eval_examples: 1000

training:
  mu_gpu: False
  num_iterations: 1
  steps_per_iteration: 3
  batch_size: 2
  num_generations: 2
  max_completion_length: 500
  beta: 0.04
  learning_rate: 5e-6
  mu: 1
  epsilon: 0.1

save_path: "save"